use crate::project::truth_file::{GeneratedField, ProjectTruthFile};
use serde_json::json;

pub fn export_markdown(project: &ProjectTruthFile, fields: &[GeneratedField]) -> String {
    let mut md = String::new();
    md.push_str("# App Store Submission Pack\n\n");
    md.push_str(&format!("Generated for: **{}**\n\n", project.app_identity.app_name));

    md.push_str("## App Information\n\n");
    md.push_str(&format!("### App Name\n{}\n\n", project.app_identity.app_name));
    if !project.app_identity.bundle_id.is_empty() {
        md.push_str(&format!(
            "### Bundle ID\n{}\n\n",
            project.app_identity.bundle_id
        ));
    }
    if !project.app_identity.version.is_empty() {
        md.push_str(&format!("### Version\n{}\n\n", project.app_identity.version));
    }

    let product_fields = ["subtitle", "promotional_text", "description", "keywords"];
    let has_product = fields.iter().any(|f| product_fields.contains(&f.field.as_str()));
    if has_product {
        md.push_str("## Product Page\n\n");
        for name in product_fields {
            if let Some(field) = fields.iter().find(|f| f.field == name) {
                md.push_str(&format!("### {}\n{}\n\n", title_case(name), field.value));
            }
        }
    }

    if let Some(field) = fields.iter().find(|f| f.field == "whats_new") {
        md.push_str("## Version Information\n\n");
        md.push_str(&format!("### What's New\n{}\n\n", field.value));
    }

    if let Some(field) = fields.iter().find(|f| f.field == "review_notes") {
        md.push_str("## App Review Notes\n\n");
        md.push_str(&format!("{}\n\n", field.value));
        if project.review.demo_account_available == Some(true) {
            md.push_str("### Demo Account\n");
            md.push_str(&format!("Username: {}\n", project.review.demo_username));
            md.push_str(&format!("Password: {}\n\n", project.review.demo_password));
        }
    }

    if let Some(field) = fields.iter().find(|f| f.field == "privacy_summary") {
        md.push_str("## Privacy Summary\n\n");
        md.push_str(&format!("{}\n\n", field.value));
    }
    if !project.privacy.privacy_policy_url.is_empty() {
        md.push_str(&format!(
            "Privacy Policy URL: {}\n\n",
            project.privacy.privacy_policy_url
        ));
    }

    let iap_fields: Vec<_> = fields
        .iter()
        .filter(|f| f.field.starts_with("iap_"))
        .collect();
    if !iap_fields.is_empty() || project.monetization.has_iap == Some(true) {
        md.push_str("## In-App Purchases\n\n");
        for field in iap_fields {
            md.push_str(&format!("### {}\n{}\n\n", title_case(&field.field), field.value));
        }
        if !project.monetization.iap_type.is_empty() {
            md.push_str(&format!(
                "IAP Type: {}\n\n",
                project.monetization.iap_type
            ));
        }
    }

    md.push_str("---\n\n");
    md.push_str("*Generated by AppMeta. Review all content before submitting to App Store Connect.*\n");
    md
}

pub fn export_json(project: &ProjectTruthFile, fields: &[GeneratedField]) -> String {
    let get = |name: &str| -> String {
        fields
            .iter()
            .find(|f| f.field == name)
            .map(|f| f.value.clone())
            .unwrap_or_default()
    };

    let doc = json!({
        "app_information": {
            "name": project.app_identity.app_name,
            "subtitle": get("subtitle"),
            "bundle_id": project.app_identity.bundle_id,
            "version": project.app_identity.version,
            "category": project.app_identity.primary_category,
        },
        "product_page": {
            "promotional_text": get("promotional_text"),
            "description": get("description"),
            "keywords": get("keywords"),
        },
        "version": {
            "whats_new": get("whats_new"),
        },
        "review": {
            "notes": get("review_notes"),
            "demo_username": project.review.demo_username,
            "demo_password": project.review.demo_password,
            "requires_login": project.review.requires_login,
        },
        "privacy": {
            "summary": get("privacy_summary"),
            "policy_outline": get("privacy_policy_outline"),
            "privacy_policy_url": project.privacy.privacy_policy_url,
        },
        "iap": {
            "display_name": get("iap_display_name"),
            "description": get("iap_description"),
            "review_notes": get("iap_review_notes"),
            "type": project.monetization.iap_type,
        },
        "generated_at": chrono::Utc::now().to_rfc3339(),
    });

    serde_json::to_string_pretty(&doc).unwrap_or_else(|_| "{}".to_string())
}

fn title_case(s: &str) -> String {
    s.split('_')
        .map(|w| {
            let mut c = w.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::project::ProjectTruthFile;

    #[test]
    fn markdown_contains_app_name() {
        let project = ProjectTruthFile::new_empty("TestApp".into(), "/tmp".into());
        let fields = vec![GeneratedField {
            field: "subtitle".into(),
            value: "Great app".into(),
            alternatives: vec![],
            character_count: 9,
            max_characters: Some(30),
            confidence: "high".into(),
            source_facts_used: vec![],
            warnings: vec![],
            missing_info: vec![],
        }];
        let md = export_markdown(&project, &fields);
        assert!(md.contains("TestApp"));
        assert!(md.contains("Great app"));
    }
}
